"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['RockRace.py']
DATA_FILES = ['Wrote', 'setup.py', 'racecar.png', 'rock.png', 'BG.jpg', 'shift.wav','crash.wav']
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
